packages:
  - ./packages/app-floors
  - ./packages/app-osm
  - ./packages/create-floors
  - ./packages/example-floors
  - ./packages/example-osm
  - ./packages/lib
  - ./packages/svgpatheditor
  - ./packages/tools-osm
  - ./packages/vscode-svgpatheditor
overrides:
  "tmp": "^0.2.4"
onlyBuiltDependencies: []
