packages:
  - ./packages/app-floors
  - ./packages/app-osm
  - ./packages/create-floors
  - ./packages/example-floors
  - ./packages/example-osm
  - ./packages/lib
  - ./packages/svgpatheditor
  - ./packages/svgpatheditor-vscode
  - ./packages/tools-floors
  - ./packages/tools-osm
overrides:
  '@types/node': '24.x'
  'Pygments': '>=2.20.0'
  'lxml': '>=6.1.0'
  'pytest': '>=9.0.3'
  'requests': '>=2.33.0'
  'urllib3': '>=2.7.0'
  'vite': '>=7.3.2'
  'tmp': '^0.2.4'
onlyBuiltDependencies: []
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  msw: true
minimumReleaseAgeExclude:
  - 'vite'
  - 'vitest'
  - '@vitest/browser'
  - '@vitest/mocker'
