packages:
  - ./packages/app-*
  - ./packages/astro-*
  - ./packages/create-*
  - ./packages/example-*
  - ./packages/lib
  - ./packages/svgpatheditor
  - ./packages/svgpatheditor-vscode
  - ./packages/tools-*
catalog:
  '@types/node': '^25.9.1'
overrides:
  '@types/node': '^24'
  '@xstate/store': '^3'
  'Pygments': '>=2.20.0'
  'lxml': '>=6.1.0'
  'pytest': '>=9.0.3'
  'requests': '>=2.33.0'
  'urllib3': '>=2.7.0'
  'vite': '>=7.3.2'
  'tmp': '^0.2.4'
onlyBuiltDependencies: []
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  msw: true
  sharp: true
minimumReleaseAgeExclude:
  - 'vite'
  - 'vitest'
  - '@vitest/browser'
  - '@vitest/mocker'
  - '@astrojs/internal-helpers@0.10.0'
  - '@astrojs/react@5.0.6'
