export const MAP_SVG_PATHS_ROOT_ID = 'map-svg-paths'
export const MAP_SVG_PATHS_CONTENT_ID = 'map-svg-paths-content'
export const MAP_SVG_OBJECTS_ROOT_ID = 'map-svg-objects'
export const MAP_SVG_OBJECTS_CONTENT_ID = 'map-svg-objects-content'
export const MAP_SVG_SYMBOLS_ROOT_ID = 'map-svg-symbols'
export const MAP_SVG_SYMBOLS_CONTENT_ID = 'map-svg-symbols-content'
export const MAP_SVG_MARKERS_ROOT_ID = 'map-svg-markers'
export const MAP_SVG_MARKERS_CONTENT_ID = 'map-svg-markers-content'
export const MAP_SVG_LABELS_ROOT_ID = 'map-svg-labels'
export const MAP_SVG_LABELS_CONTENT_ID = 'map-svg-labels-content'
export const MAP_HTML_ROOT_ID = 'map-html'
export const MAP_HTML_CONTENT_ID = 'map-html-content'

export const MAP_SVG_FLOORS = 'map-svg-floors'
