export const MAP_SVG_ROOT_ID = 'map-svg'
export const MAP_SVG_CONTENT_ID = 'map-svg-svg'
export const MAP_SVG_SYMBOLS_ROOT_ID = 'map-svg-symbols'
export const MAP_SVG_SYMBOLS_CONTENT_ID = 'map-svg-symbols-svg'
export const MAP_SVG_MARKERS_ROOT_ID = 'map-svg-markers'
export const MAP_SVG_MARKERS_CONTENT_ID = 'map-svg-markers-svg'
export const MAP_SVG_LABELS_ROOT_ID = 'map-svg-labels'
export const MAP_SVG_LABELS_CONTENT_ID = 'map-svg-labels-svg'
