# yaml-language-server: $schema=../../../node_modules/svgmapviewer-astro-floors/src/utils/schema/svgMapViewerConfigUser.schema.json
root: root
title: Floor Map Test
zoomFactor: 2
origViewBox:
  x: 0
  y: 0
  width: 220
  height: 300
origBoundingBox:
  x: 0
  y: 0
  width: 220
  height: 300
