#!/usr/bin/env python3

import argparse
import json
import math
import sys
import typing


LAYER_DEFAULT = 'Main'
LINE_HEIGHT = 1.25
FONT_FAMILY="'Noto Sans', sans-serif"
FONT_SIZE = 16
FONT_WEIGHT = 200
AREA_RATIO = 0.25


# generated by gen-labels.py
class LabelParams(typing.TypedDict):
    name: str
    pat: str
    s: float
    dy: float
    area: float


# edited & saved by inkscape
class FloorAddress(typing.TypedDict):
    x: float
    y: float
    area: float | None
    rx: float | None
    ry: float | None
    rotate: float | None


class LabelTspan(typing.TypedDict):
    attrs: dict[str, str]
    text: str


class LabelText(typing.TypedDict):
    attrs: dict[str, str]
    children: list[LabelTspan]


####

layer = LAYER_DEFAULT
line_height = LINE_HEIGHT
font_family = FONT_FAMILY
font_size = FONT_SIZE
font_weight = FONT_WEIGHT
area_ratio = AREA_RATIO


params: list[LabelParams] = []
addresses: dict[str, FloorAddress] = {}
names: dict[str, list[str]] = {}
address_to_names: dict[str, list[str]] = {}
name_to_params: dict[str, LabelParams] = {}
name_to_params_nowrap: dict[str, LabelParams] = {}

texts: list[LabelText] = []


layer = 'B1F'
labels_json = f"labels-{layer}.json"
labels_nowrap_json = f"labels-nowrap-{layer}.json"
floors_addresses_json = f"floors-addresses-{layer}.json"
floors_names_json = f"floors-names-{layer}.json"
floors_labels_json = f"floors-labels-{layer}.json"


def prepare():
    global address_to_names
    global addresses
    global name_to_params
    global name_to_params_nowrap
    global names
    global params

    with open(labels_json, "r", encoding="utf-8") as fh:
        #global params
        params = json.load(fh)
        for param in params:
            name = param['name']
            name_to_params[name] = param

    with open(labels_nowrap_json, "r", encoding="utf-8") as fh:
        #global params
        params = json.load(fh)
        for param in params:
            name = param['name']
            name_to_params_nowrap[name] = param

    with open(floors_addresses_json, "r", encoding="utf-8") as fh:
        #global addresses
        addresses = json.load(fh)

    with open(floors_names_json, "r", encoding="utf-8") as fh:
        #global addresses
        names = json.load(fh)
        for name, astrs in names.items():
            for astr in astrs:
                address_to_names.setdefault(astr, []).append(name)


def make_label_text(words: list[str], transform: str) -> LabelText:
    tspans: list[LabelTspan] = []
    for idx, word in enumerate(words):
        tspan: LabelTspan = {
            'attrs': {
                'x': '0',
                'y': f"{line_height * idx}em",
            },
            'text': word,
        }
        tspans.append(tspan)
    text: LabelText = {
        'attrs': {
            'font-family': f"{font_family}",
            'font-weight': f"{font_weight}",
            'font-size': f"{font_size}px",
            'text-anchor': 'middle',
            'transform': transform,
        },
        'children': tspans,
    }
    return text


def make_label_text_long(words: list[str], transform: str) -> LabelText:
    name = ' '.join(words)
    print(f"long: {name}", file=sys.stderr)
    return make_label_text([name], transform)


def calc_transform(point: FloorAddress, name: str) -> (str, bool):
    dst = point['area']
    #print(f"{name}: params.area={src} point.area={dst} s={round(s, 2)}")
    x = point['x']
    y = point['y']
    rx = point['rx']
    ry = point['ry']

    aratio = rx / ry if rx > ry else ry / rx
    long = aratio > 4
    ##if long:
    ##    print(f"long: point={point} params={params}")

    params = name_to_params[name] if not long else name_to_params_nowrap[name]
    src = params['area']
    s = params['s']
    dy = params['dy']

    rotate = 0 if ry / rx < 1.01 else 90

    scale2 = dst * area_ratio / src
    scale = round(math.sqrt(scale2), 4)

    return (f"translate({x}, {y}) rotate({rotate}) scale({scale}) scale({s}) translate(0, {-dy})", long)


def proc_name(point: FloorAddress, name: str):
    global texts

    (transform, long) = calc_transform(point, name)
    words = name.strip().split(' ')

    text = make_label_text(words, transform) if not long else make_label_text_long(words, transform)
    texts.append(text)


def proc() -> None:
    global texts

    for astr, point in addresses.items():
        if astr not in address_to_names:
            continue
        names = address_to_names[astr]
        # XXX
        # XXX
        # XXX
        name = names[0]
        # XXX
        # XXX
        # XXX
        proc_name(point, name)


def main() -> None:
    global area_ratio
    global font_family
    global font_size
    global font_weight
    global layer
    global line_height

    p = argparse.ArgumentParser()
    p.add_argument('layer', type=str, help='layer (e.g. "1F")')
    p.add_argument('-a', '--area-ratio', type=float)
    p.add_argument('-F', '--font-family', type=str)
    p.add_argument('-f', '--font-size', type=float)
    p.add_argument('-w', '--font-weight', type=float)
    p.add_argument('-l', '--line-height', type=float)
    args = p.parse_args()

    if args.area_ratio is not None:
        area_ratio = args.area_ratio
    if args.font_family is not None:
        font_family = args.font_family
    if args.font_size is not None:
        font_size = args.font_size
    if args.font_weight is not None:
        font_weight = args.font_weight
    if args.line_height is not None:
        line_height = args.line_height
    layer = args.layer

    global labels_json
    global floors_addresses_json
    global floors_names_json
    global floors_labels_json

    labels_json = f"labels-{layer}.json"
    floors_addresses_json = f"floors-addresses-{layer}.json"
    floors_names_json = f"floors-names-{layer}.json"
    floors_labels_json = f"floors-labels-{layer}.json"

    prepare()
    proc()
    with open(floors_labels_json, "w", encoding="utf-8") as fh:
        json.dump(texts, fh, ensure_ascii=False, indent=2)


if __name__ == '__main__':
    main()
